import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dox Search",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="ml-8 mt-4">
        <Image src={'/images/logo.jpg'} alt="Dox Search" width="100" height="100" />
        </section>
        {children}
        </body>
    </html>
  );
}
